name: TomLib
version: 1.2.6
date: 2016-11-07
description: |
    The GAP Library of Tables of Marks

authors:
    - name: Götz Pfeiffer
      url: mailto:goetz.pfeiffer@nuigalway.ie

maintainers:
    - name: Liam Naughton
      url: http://schmidt.nuigalway.ie

GAP: ">= 4.4"

needed-pkgs:
    - name: "atlasrep"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep"

suggested-pkgs:
    - name: "ctbllib"
      version: ">= 1.1"
      url: "http://www.math.rwth-aachen.de/~Thomas.Breuer/ctbllib"

www: http://schmidt.nuigalway.ie/tomlib
readme: README
packageinfo: http://schmidt.nuigalway.ie/tomlib/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://schmidt.nuigalway.ie/tomlib/tomlib1r2p6.tar.gz

abstract: |
    The package contains the <span class="pkgname">GAP</span> Library of Tables of Marks

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    table of marks, Burnside matrix, subgroup lattice, finite simple groups, Moebius function, Euler function.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NP16</span>]   <b class='BibAuthor'>Naughton, L. and Pfeiffer, G.</b>,
     <i class='BibTitle'>TomLib, The GAP Library of Tables of Marks,
             Version 1.2.6</i>
     (<span class='BibYear'>2016</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="http://schmidt.nuigalway.ie/tomlib">http://schmidt.nuigalway.ie/tomlib</a></span>.
    </p>
    

bibtex: |
    @misc{ TomLib1.2.6,
      author =           {Naughton, L. and Pfeiffer, G.},
      title =            {{TomLib}, The GAP Library of Tables of Marks, {V}ersion 1.2.6},
      month =            {Nov},
      year =             {2016},
      note =             {GAP package},
      howpublished =     {\href {http://schmidt.nuigalway.ie/tomlib} {\texttt{http://schmidt.nuigalway.ie/}\discretionary {}{}{}\texttt{tomlib}}},
      keywords =         {table of marks; Burnside matrix; subgroup lattice; finite simple groups; Moebius function; Euler function},
      printedkey =       {NP16}
    }

